# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dab17138158eca3fc486360ed562c3aacaccac70a4b6b5fd7874abb0e9d97637365f649f35a6fe0a8dd2717ae2b30ed8a347cf9f3c562aa7e077707ef22e1c8e

test:
  secret_key_base: b0c6bf4be3549156b162d4cc2854c41512215f3403d90926a590d5d44c78022b805e0f543c1ff37e7abcb78e79db0ca414b0e80bb9af8d611d499d1ffff2730a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
